[package]
name = "tredc"
version = "0.1.0"
authors = ["Sam Sartor <me@samsartor.com>"]

[features]
default = ["aster/with-syntex", "syntex_syntax"]
nightly = []

[dependencies]
aster = { version = "*", default_features = false }
syntex_syntax = { version = "*", optional = true }